# Generated by Django 4.1.3 on 2022-12-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description_task', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'doing'), (2, 'done')], default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
